### ISSUE TITLE
Manejo de datos

### ISSUE THREAD

**Issue by euphonie** [bakedintime/cineTir#1]
¿Qué se va a utilizar para almacenamiento de la información y de qué tipo?

Tipos:
- NoSQL (como MongoDB)
- SQL (MySQL o PostgreSQL)

Opciones: 
- compose.io

**Comment by euphonie** [comment]
Compose.io sería una solución de BaaS (backend as a service) para que desde cualquier dispositivo podamos probar el API. Puede ser otro servicio pero recomiendo que sea siempre un BaaS.

**Comment by cancinos** [comment]
Si se utiliza compose.io supondría algún costo económico? En la página https://www.compose.io/ ofrecen un trial de 30 días, pero no estoy seguro si luego haya que invertir en una licencia. Me agradaría mantenerlo todo open-source.

**Comment by euphonie** [comment]
Tengo cuenta en http://heroku.com y desde ahí puedo crear una BD gratuita  de Postgresql.
